### ISSUE TITLE
Override how often we check for auth

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/cli#268]
I know Auth0 wants us to check for auth every 5 seconds but that's ridiculous, we should reduce this to maybe every 1s

**Comment by DavidS-ovm** [comment]
The oauth2 RFC requires and the library implements a basic 5s delay, and Auth0's API asks for slower requests (causing the delay to increase by 5s each time) when I tried forcing this to a lower cadence.

For reference the code I used:
```diff
diff --git a/cmd/tea_ensuretoken.go b/cmd/tea_ensuretoken.go
--- a/cmd/tea_ensuretoken.go
+++ b/cmd/tea_ensuretoken.go
@@ -229,6 +232,16 @@ func (m ensureTokenModel) oauthTokenCmd() tea.Msg {
 }
 
 func (m ensureTokenModel) awaitTokenCmd() tea.Msg {
+       if m.deviceCode != nil {
+               // while the RFC requires the oauth2 library to use 5 as the default,
+               // Auth0 should be able to handle more. This sets the Interval
+               // conditionally to 1 if and only if the requested interval is the
+               // default or less, so that IF Auth0 requests a slowdown (which causes 5
+               // seconds to be added), we will not override that.
+               if m.deviceCode.Interval <= 5 {
+                       m.deviceCode.Interval = 1
+               }
+       }
        token, err := m.config.DeviceAccessToken(m.ctx, m.deviceCode)
        if err != nil {
                return fatalError{id: m.spinner.ID(), err: fmt.Errorf("error authorizing token: %w", err)}
```

To work around this, we'd have to fork the oauth2 library, and then we're still depending on Auth0 not locking us out of the API completely.

I also evaluated whether we can prompt the user to confirm once they've clicked the button in Auth0, but the way the oauth2 library is written (https://cs.opensource.google/go/x/oauth2/+/master:deviceauth.go;l=140-198) means that in the best case we would be calling `DeviceAccessToken()` with `da.Interval == 1` (zero seconds would trigger the 5s initial delay), and the user would still have to wait for 1s AND the time it takes to `retrieveToken()`. I don't think that is worth the additional hassle of an extra prompt.
