### ISSUE TITLE
cli: update actions to use new terraform subcommands with built-in sources

### ISSUE THREAD

**Issue by DavidS-ovm** [overmindtech/cli#289]

**Comment by dylanratcliffe** [comment]
I'm doing some ticket cleanup. What does this one mean?

**Comment by DavidS-ovm** [comment]
Does the new title make more sense?

**Comment by dylanratcliffe** [comment]
Oh Github actions?

**Comment by dylanratcliffe** [comment]
Yeah not for this week, I'll remove from the milestone

**Comment by DavidS-ovm** [comment]
Closing this because bubbletea tty handling and github TTY emulation are not very compatible.
