### ISSUE TITLE
cli: word-wrap all bubbletea View() output to terminal size

### ISSUE THREAD

**Issue by DavidS-ovm** [overmindtech/cli#291]
This is from https://github.com/overmindtech/cli/issues/270:

> The 2nd last error (the same one as in the first line is truncated, but not the one that is wrapped) is truncated, it ends with "no such hos"

it happens because https://github.com/overmindtech/cli/blob/8601c728a5cac40c9fce5e2b53da017833d61afc/cmd/terraform_plan.go#L382 doesn't do line wrapping.

Since we don't do this here or anywhere else, the issue probably applies to everything and requires a holistic solution. For now, the `markdownToString` version on `cmdModel` suffices

**Comment by dylanratcliffe** [comment]
@DavidS-ovm This is done right?

**Comment by DavidS-ovm** [comment]
> @DavidS-ovm This is done right?

not in all places.
