### ISSUE TITLE
revlink warmup status sometimes is not saved correctly

### ISSUE THREAD

**Issue by DavidS-ovm** [overmindtech/cli#358]
Sometimes I observe that multiple consecutive runs of the CLI do have to wait for revlink warmup, when a single one should suffice. Probably a bug in the finalisation code.

**Comment by dylanratcliffe** [comment]
This is *basically* the way it's supposed to work. Ideally we'd be smarter about this but we will hold off on this until we have improved the way sources report and are tracked in general i.e.

* Revlink on a per-source basis
* Having the server understand which sources are available

...etc
