### ISSUE TITLE
Spinners don't render in Powershell or Command Prompt

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/cli#388]
<img width="557" alt="Screenshot 2024-06-11 at 2 56 40 PM" src="https://github.com/overmindtech/cli/assets/8799341/7ed46d1a-8b3a-440e-9e5b-ac7e27bbb3a7">

The fonts that are used here don't seem to support the emojis. If you copy-paste into something else it works fine, so i'm assuming it's the fonts, we will have to switch so something mega-basic when we are on these shells.

Here's where this is printed in code: https://github.com/overmindtech/cli/blob/0c0fd070fd3e32ed31792c522d081d3a70c2d936/cmd/tea_taskmodel.go#L121-L123

**Comment by DavidS-ovm** [comment]
PowerShell community discord confirmed multiple times that the default terminal (conhost) won't display emojis. The new Windows Terminal can, but is an optional component.

@dylanratcliffe I'm worried that WSL also might run in conhost (what else would it be) and thus using the linux build won't work either. Can you check that on your windows instance?

**Comment by dylanratcliffe** [comment]
Confirmed that WSL also doesn't have good fonts: 

<img width="791" alt="Screenshot 2024-06-12 at 9 41 54 AM" src="https://github.com/overmindtech/cli/assets/8799341/b7f22b17-c32b-4af7-af2d-b426c45ae8bf">

**Comment by dylanratcliffe** [comment]
We can detect that we are running under WSL like so:

```
$ cat /proc/version
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #4355-Microsoft Thu Apr 12 17:37:00 PST 2024
```

**Comment by dylanratcliffe** [comment]
<img width="1161" alt="Screenshot 2024-06-12 at 9 52 31 AM" src="https://github.com/overmindtech/cli/assets/8799341/91c0cf94-1551-4019-9d34-0f9fa2097d70">

Windows terminal works great through and can be determined by checking the value of the `WT_SESSION` env var:

```
> $env:WT_SESSION
ded037c6-04c4-4a69-a9e7-ab55ecb7b165
```

**Comment by dylanratcliffe** [comment]
So in summary we have the following:

* Any linux terminal: **Fine ✅**
* Powershell: **Terrible 😢**
* CMD: **Terrible 😢**
* Windows Terminal: **Fine ✅**
* WSL: **Terrible 😢** (However the linux-based packages do work)

So I think the sanest thing we can do is try to detect the correct spinners to use:

* IF linux
  * IF `/proc/version` contains `Microsoft`: Boring spinners
  * ELSE cool spinners
* IF Windows
  * IF env var `WT_SESSION` is set: Cool spinners
  * ELSE: Boring spinners

**Comment by DavidS-ovm** [comment]
I've poked around a bit at conhost (the default windows terminal emulator) and [Windows Terminal](https://github.com/microsoft/terminal) (the shiny new thing) and there's only pain and suffering down this path. See also: https://github.com/microsoft/terminal/issues/7434

When using Windows Terminal, WT_SESSION also exists in WSL processes, so the amended decision tree is: `WT_SESSION is set || is linux` 

Of course this still can cause false positives (when conhost is loaded from WT and has WT_SESSION set without the capabilities), but clearly the Windows Terminal folks are not interested in solving this problem, so we're out of luck then.

**Comment by dylanratcliffe** [comment]
<img width="1212" alt="Screenshot 2024-06-12 at 8 07 54 PM" src="https://github.com/overmindtech/cli/assets/8799341/b937d153-cb1b-4e2e-8826-6f68a559b57b">

Windows Terminal with WSL looks fine to me
