### ISSUE TITLE
Cannot be opened because apple cannot check it for malicious software

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/cli#82]
When opening the CLI for the first time we get this error:

<img width="297" alt="Screenshot 2023-10-04 at 5 05 29 pm" src="https://github.com/overmindtech/ovm-cli/assets/8799341/705aa0c1-5eb2-4e71-96ed-477ea5765336">

We should be able to fix this

Developer ID: https://developer.apple.com/developer-id/

**Comment by dylanratcliffe** [comment]
I've requested a D-U-N-S number which is a pre-requisite for the apple developer program. However we will also need an installer since you can't just sign a binary apparently, it needs to be disk image or something like that. For that we should look into creating homebrew packages

**Comment by dylanratcliffe** [comment]
Seems that [Gon](https://github.com/mitchellh/gon) is the best way to do this for mac at least. We'd get goreleaser to spit out a DMG, then Gon to sign it. We'll need to wait for our developer account so I can get the cert though. We'll then need another process on top that takes that DMG and wraps it in a homebrew package if we want a nice installer (which we do)

**Comment by DavidS-ovm** [comment]
Can we consider this fixed through the brew installer?

**Comment by dylanratcliffe** [comment]
Yep!
